# threshold = 4.5
excluded_segments = {
    'M9_7': {
        'region1': {
            1: [7],
            3: 'all',
            7: [4],
            9: [7],
            17: 'all',
            19: 'all',
            28: 'all',
            32: 'all',
            34: 'all',
            39: 'all'
        },
        'region2': {
            2: [6],
            5: 'all',
            7: 'all', 
            8: 'all', 
            9: 'all', 
            11: 'all', 
            12: 'all', 
            13: 'all', 
            19: [7],
            26: 'all',
            30: 'all',
            31: 'all',
            33: 'all',
            36: 'all',
            38: [0],
            41: [0],
            43: [0],
            49: [2],
            50: 'all',
            51: 'all',
            52: 'all',
        }
    },
}

# threshold = 5.5
# symmetry = 0.95
excluded_segments = {
    'M9_7': {
        'region1': {
            1: [2],
            2: 'all',
            19: 'all',
            29: 'all',
            33: 'all',
            35: 'all',
            39: 'all',
        },
        'region2': {
            4: 'all',
            5: 'all',
            6: 'all',
            7: 'all',
            8: 'all',
            9: 'all',
            10: 'all',
            11: 'all',
            12: 'all',
            33: [0, 4],
            37: [5, 7],
            38: 'all',
            47: 'all',
            48: 'all',
            49: 'all',
            50: 'all',
        }
    },
    'M9_8': {
        'region1': {
            1: 'all',
            3: 'all',
            15: 'all',
            17: 'all',
            19: 'all',
            20: 'all',
        },
        'region2': {
            11: 'all',
            12: 'all',
            18: 'all',
            22: 'all',
            30: 'all',
            36: 'all',
        },
    },
    'M10_1': {
        'region1': {
            1: 'all',
            3: [0],
            5: 'all',
            6: 'all',
            7: [4],
            10: 'all',
            11: 'all',
            12: [4],
            13: 'all',
            14: 'all',
            15: 'all',
            16: 'all',
            17: 'all',
            18: 'all',
            19: 'all',
            20: 'all',
            21: 'all',
            22: 'all',
            23: 'all',
            25: 'all',
            31: 'all',
            36: 'all',
            53: 'all',
            54: 'all',
            55: 'all',
            56: 'all',
            57: 'all',
            58: 'all',
            59: 'all',
            60: 'all',
            62: 'all',
            63: 'all',
        },
        'region2': {
            2: 'all',
            17: 'all',
            31: 'all',
            38: 'all',
            39: 'all',
            40: 'all',
            42: 'all',
            43: 'all',
            44: 'all',
            45: 'all',
            46: 'all',
            47: 'all',
            48: 'all',
            49: 'all',
            50: 'all',
        },
    },
    'M10_6': {
        'region1': {
            1: 'all',
            4: 'all',
            5: 'all',
            7: 'all',
            8: 'all',
            9: 'all',
            10: 'all',
            11: 'all',
            13: 'all',
            14: 'all',
            15: 'all',
            16: 'all',
            17: 'all',
            18: 'all',
            36: 'all',
        },
        'region2': {
            14: 'all',
            23: 'all',
            37: 'all',
            44: 'all',
        },
    },
    'M15_2': {
        'region1': {
            2: 'all',
            3: 'all',
            4: 'all',
            9: [1],
            11: 'all',
            43: 'all',
            44: 'all',
            49: 'all',
            61: 'all',
        },
        'region2': {
            2: 'all',
            4: 'all',
            15: 'all',
            17: 'all',
            21: 'all',
            26: 'all',
            30: 'all',
            31: 'all',
            34: 'all',
            35: 'all',
            36: 'all',
            37: 'all',
        },
    },
    'M15_3': {
        'region1': {
            5: 'all',
            8: 'all',
            11: [1],
            19: 'all',
        },
        'region2': {
            28: 'all',
            34: 'all',
            36: [3],
            38: 'all',
            40: 'all',
            42: 'all',
            49: 'all',
        },
    },
    'M15_5': {
        'region1': {
            1: 'all',
            6: 'all',
            20: 'all',
            29: [0],
        },
        'region2': {
            5: 'all',
            8: 'all',
            28: 'all',
            30: 'all',
            41: 'all',
        },
    },
    'M15_7': {
        'region1': {
            5: 'all',
            11: 'all',
            31: 'all',
        },
        'region2': {
            3: 'all',
            55: 'all',
        },
    },
    'M16_1': {
        'region1': {
            10: [2, 3],
            17: 'all',
            29: 'all',
            47: 'all',
            48: 'all',
            76: 'all',
        },
        'region2': {
            5: 'all',
            19: 'all',
            26: 'all',
            28: 'all',
            33: 'all',
            34: 'all',
            38: 'all',
            39: 'all',
        }
    }
}
